export APP_RAILWAY_DATABASE_HOST="localhost"
export APP_RAILWAY_DATABASE_NAME="app_railway"
export APP_RAILWAY_DATABASE_USERNAME="matu47"
export APP_RAILWAY_DATABASE_PASSWORD="Manchita47"
export TEST_APP_RAILWAY_DATABASE_HOST="localhost"
export TEST_APP_RAILWAY_DATABASE_NAME="app_railway_test"
export TEST_APP_RAILWAY_DATABASE_USERNAME="matu47"
export TEST_APP_RAILWAY_DATABASE_PASSWORD="Manchita47"

